version: "3.7"

services:
  mysql:
    image: mysql:8.0
    ports:
      - 8881:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: roach
      MYSQL_DATABASE: todos